# Generated by Django 5.0.14 on 2026-06-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_type', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('affected_url', models.CharField(max_length=2048)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scan')),
            ],
        ),
    ]
