# Generated by Django 5.0.14 on 2026-06-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_remediation', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airemediation',
            name='vulnerability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_remediation', to='vulnerabilities.vulnerability'),
        ),
    ]
